package com.wellnesscookie.pravnainformatika.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CaseRecord(
    val id: String,
    val caseNumber: String = "",
    @SerialName("case_id") val caseId: String? = null,
    val type: String = "",
    val court: String = "",
    val date: String = "",
    val verdict: String = "",
    val articles: List<String> = emptyList(),
    val sentence: String = "",
    val sentenceMonths: Int = 0,
    val defendant: String = "",
    val keywords: List<String> = emptyList(),
    val caseDescription: String = "",
    val evidence: String = "",
    val sudija: String = "Nepoznat",
    val zapisnicar: String = "Nepoznat",
    val uslovnaOsuda: Boolean = false,
    val ranijeOsudjivan: String = "",
    val svjedoci: List<String> = emptyList(),
    val dokazi: List<String> = emptyList(),
    val clanKZ: String = "",
    val tipKrivicnogDjela: String = "",
    val brojOkrivljenih: Int = 1,
    val brojSvjedoka: Int = 0,
    val brojDokaza: Int = 0,
    val generatedBy: String = "",
    // Environmental-crime fields
    val saizvrsilastvo: String = "ne",
    val zabranjenoSredstvo: String = "ne",
    val lovostajIliZabranjeneVode: String = "ne",
    val velikaKolicina: String = "ne",
    val elektricnaStruja: String = "ne",
    val agregat: String = "ne",
    val sonda: String = "ne",
    val pretvarac: String = "ne",
    val prisutanUlov: String = "ne",
    val kolicinaUlovaKg: Double = 0.0,
    val oduzimanjePredmeta: String = "ne",
    val kaznaZatvoraMjeseci: Int = 0,
    val kaznaZatvoraDani: Int = 0,
    val radUJavnomInteresuCasovi: Int = 0,
    val rokProvjereGodine: Int = 0,
    val troskoviEur: Double = 0.0,
    // Hunting-specific (čl. 325). lovostajIliZabranjeneVode is shared: covers
    // both fishing "zabranjene vode" and hunting "lovostaj/zabranjeno područje".
    val tudjeLoviste: String = "ne",
    val krupnaDivljac: String = "ne",
    val zasticenaVrsta: String = "ne",
    val bezPosebneDozvole: String = "ne",
    val masovnoUnistavanje: String = "ne",
    val vatrenoOruzje: String = "ne",
    val lovackiPsi: Int = 0,
    val bezOruznogLista: String = "ne",
    val bezDozvoleZaLov: String = "ne",
    val odstreljenaDivljac: String = "ne",
    val vrstaDivljaci: String = "",
    val brojGrlaDivljaci: Int = 0,
    val sticajDrugogDela: String = "ne",
    val year: Int = 2024,
    val xmlFile: String? = null,
)
